### ISSUE TITLE
Not working with Karma and Webpack 4

### ISSUE THREAD

**Issue by popod** [ashtuchkin/iconv-lite#204] opened 2018-10-06 18:28 UTC
Hi,

I've a strange bug. All works correctly when I run my application in production, but I can't run my unit tests because of your module.. Removing all `require('iconv-lite')` in my code resolve the problem.

I'm using Webpack 4, Karma 3, ES6.

This is the error I get:

```
Electron 3.0.2 (Node 10.2.0) ERROR
  {
    "message": "Uncaught TypeError: __webpack_require__(...) is not a function\nat webpack:///app/node_modules/iconv-lite/lib/index.js:144:27 <- index.js:58520:48\n\nundefined",
    "str": "Uncaught TypeError: __webpack_require__(...) is not a function\nat webpack:///app/node_modules/iconv-lite/lib/index.js:144:27 <- index.js:58520:48\n\nundefined"
  }
```

Have you any Idea of what this could be ? Thanks

**Comment by ashtuchkin** [comment] 2018-10-07 22:19
I'm not familiar with Karma and have very little experience with Electron,
but my guess would be that there's some magic happening in the unit test
environment that doesn't work well with dynamic require()-s. Iconv-lite
only loads conversion tables on demand, as they take 100s of ms to load.
That might not work too well if the environment pre-packages the files
based on static require()-s.

You can check it by adding require("iconv-lite/encodings") somewhere in
your code.

Let me know how it went.

**Comment by popod** [comment] 2018-10-08 08:36
Hi,

Thanks for your reply. I think this is not an Electron issue, but really a karma issue. Include `require('iconv-lite/encodings')` change nothing for me.

If I follow to the line number (144) pointed by the error, the problem appear with the `require('./stream')` in the `index.js` file:

```
// Load extensions in Node. All of them are omitted in Browserify build via 'browser' field in package.json.
var nodeVer = typeof process !== 'undefined' && process.versions && process.versions.node;
if (nodeVer) {

    // Load streaming support in Node v0.10+
    var nodeVerArr = nodeVer.split(".").map(Number);
    if (nodeVerArr[0] > 0 || nodeVerArr[1] >= 10) {
        require("./streams")(iconv);     // -> this is the line 144 who do the error !
    }

    // Load Node primitive extensions.
    require("./extend-node")(iconv);
}

if ("Ā" != "\u0100") {
    console.error("iconv-lite warning: javascript files use encoding different from utf-8. See https://github.com/ashtuchkin/iconv-lite/wiki/Javascript-source-file-encodings for more info.");
}
```

**Comment by ashtuchkin** [comment] 2018-10-08 08:51
This is also a dynamic import - can you also put require("iconv-lite/streams")
and require("iconv-lite/extend-node") in your code (in addition to
require('iconv-lite/encodings'))?
--
Alexander Shtuchkin

**Comment by popod** [comment] 2018-10-08 09:48
Thanks for help, but still not working.. Here is a test project that you can use to reproduce the error.

```
git clone https://github.com/popod/iconv-test.git
cd iconv-test/
npm install
```

by running `npm run unit` you should see the error above. If your delete all the `<script>` tag and all it's content in `iconv-test/app/src/renderer/App.vue` and re-run `npm run unit` all will works normally.

**Comment by rememberjack** [comment] 2018-10-08 18:43
I ran into the same issue in an electron environment (using [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder)).

I believe the problem originates from these configurations:

1. When building electron app, webpack is configured to use [target](https://webpack.js.org/configuration/target/) 'web' or 'electron-renderer'.
2. This webpack target in turn takes [browser property](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module) into account. In this case, webpack ignores streams.js and extend-node.js from bundling because they are [set to false in the browser property in the package.json](https://github.com/ashtuchkin/iconv-lite/blob/master/package.json#L29).
3. [index.js checks for node process and environment](https://github.com/ashtuchkin/iconv-lite/blob/master/lib/index.js#L138) to determine if it is in a node environment. But in the case of electron, it is both a browser environment and a node environment. So iconv thinks it is in a node environment when the bundler thinks it is bundling for a web environment. This leads to `__webpack_require__(...) is not a function` error because streams.js is never bundled.

**Comment by popod** [comment] 2018-10-10 14:22
Thanks for your feedback and explanations @rememberjack ! Have you found a workaround for fix this?

@ashtuchkin have you planned to fix this for Electron ? Thanks in advance!

**Comment by whitehat101** [comment] 2018-10-16 22:52
This is more or less same issue as I ran into (and found a fix #203) while using mailparser with Webpack.

https://github.com/ashtuchkin/iconv-lite/blob/696be8a260a9988caba0092bb5a734a96ff9bf58/lib/index.js#L138-L145

Webpack doesn't like `require(...)(...)`. It transforms the `require()` into an empty object which can't be invoked as a function. My environment didn't define `process `, but when I persuaded the code to enter the if block, I got the same `__webpack_require__(...) is not a function` error.

Getting rid of the  `require(...)(...)` and rewriting `./streams` to `require('iconv-lite')` instead of `module.export`ing a function, fixes the error and provides a functional iconv-lite with stream support in a Webpack environment.

**Comment by popod** [comment] 2018-10-22 15:30
Hi @ashtuchkin 

Have you planned to fix this (by merging the PR #203 ?) or something else ? Thanks !

**Comment by popod** [comment] 2018-10-23 01:16
As @Feverqwe said in #205 : adding

```
{
  test: /node_modules[\/\\](iconv-lite)[\/\\].+/,
  resolve: {
    aliasFields: ['main']
  }
}
```

to the webpack `module.rules` solve my problem. Thanks for the workaround !

But I think that @whitehat101 PR #203 is a better solution and hope it will be merged soon.

**Comment by joostblok** [comment] 2018-11-29 16:55
Am having this issue as well @whitehat101 solution fixed my problem, however would love to see this merged because it's a deep dependency which might get changed again if I update my node_modules.

**Comment by Qualinost1** [comment] 2018-12-05 12:47
I'm also facing the same problem in an angular/electron env using webpack. 
Could someone describe step by step the @whitehat101 solution please?

**Comment by joostblok** [comment] 2018-12-05 16:13
@Qualinost1 open `your-project-folder/node_modules/iconv-lite/lib/index.js` in a text editor. Then change the`require('something')()` statements on line 145 and 148 to `require('iconv-lite')`

**Comment by Qualinost1** [comment] 2018-12-05 16:52
Thanks! I actually commented the test and write one require('iconv-lite').

**Comment by FibreFoX** [comment] 2018-12-12 13:19
I can confirm the workaround/fix(?) from @joostblok worked for me, but I have no idea what this does 😄

**Comment by 2507483326** [comment] 2019-01-31 05:35
modify  require("./streams")(iconv);  require("./streams.js")(iconv);  
modify  require("./extend-node")(iconv);  require("./extend-node.js")(iconv);  
can hack the problem

**Comment by kosimas** [comment] 2019-11-22 19:27
@2507483326 Thanks dude! This fixed it for me!

**Comment by peanutguo** [comment] 2020-03-05 06:41
> modify `require("./streams")(iconv);` to `require("./streams.js")(iconv); `
> modify `require("./extend-node")(iconv);` to `require("./extend-node.js")(iconv); `
> can hack the problem

it works

**Comment by appinteractive** [comment] 2020-04-22 18:49
will this be solved anytime soon?

**Comment by ashtuchkin** [comment] 2020-05-18 04:33
Thanks everyone for the context, pull request and your patience!

I have rewritten the conditional require() logic in the latest commit on master, which should fix this issue. Could somebody from this thread please confirm it please? You can do it by using the following in your package.json:
```
    "dependencies": {
        "iconv-lite": "ashtuchkin/iconv-lite",
        ...
```
(this uses https://docs.npmjs.com/files/package.json#github-urls)

**Comment by bruceCzK** [comment] 2020-05-18 05:16
Tested, works great.

**Comment by bruceCzK** [comment] 2020-05-18 05:55
And here's a working example
https://bruceczk.github.io/iconv-lite-browser-example/

You can find the source code here 
https://github.com/bruceCzK/iconv-lite-browser-example

**Comment by ashtuchkin** [comment] 2020-05-18 05:59
heh, really nice! thank you!

**Comment by ashtuchkin** [comment] 2020-05-18 06:03
I'm wondering if it can be made to work with streaming API so that we don't need to keep both encoded and decoded data in memory?

**Comment by ashtuchkin** [comment] 2020-05-18 06:11
Hmm so that project is using v0.5.1, not master branch (see https://github.com/bruceCzK/iconv-lite-browser-example/blob/master/package.json#L14).. So we probably need some other configuration that wasn't actually working on v0.5.1, like maybe Karma/Webpack?

**Comment by ryoha000** [comment] 2020-06-02 14:52
Hello.
I wanted to use a library that depended on this in my Electron project.
Then I encountered this issue and forked the used library to use this master.
Then my Electron project worked fine.
I am very grateful for the resolution of this issue.
Thank you!
I don't have the time, so it's not the minimum configuration, but I'll put some links.
[Libraries using icons-lite (package.json)](https://github.com/ryoha000/whatwg-encoding/blob/1ca990dcf1404258f4eff0dcbc9d4432b7b5124b/package.json#L22)
[Libraries using ↑(package.json)](https://github.com/ryoha000/jsdom/blob/2f9a87bfcbbe7ac6e191c1f6e2a1909553450f32/package.json#L44)
[My Electron project (package.json)](https://github.com/ryoha000/es-client/blob/90ff57a6f383d4bd3596a07dbe1a300865feb40a/package.json#L42)

**Closed** 2020-06-08 08:58 UTC

**Comment by ashtuchkin** [comment] 2020-06-08 09:04
This is fixed in v0.6.0

**Comment by eamodio** [comment] 2020-06-11 03:00
@ashtuchkin is there a way to exclude the streaming api outside of the browser? (to limit bundle size)

**Comment by ashtuchkin** [comment] 2020-06-11 05:05
It depends on how you create the bundle. Just excluding 'stream' module
should work fine.

**Comment by appinteractive** [comment] 2020-06-12 07:02
@ashtuchkin could you provide an example of how to achieve this?

**Comment by ashtuchkin** [comment] 2020-06-12 07:53
Both browserify and webpack will exclude streams module by default, so just
using any of these tools in default mode should work.

Do you have any specific problem? If yes, then could you open a new issue
and describe it, ideally with a way to reproduce it?

This issue is about iconv-lite throwing exception when used with Webpack
and Karma and I wanted to keep unrelated discussions separate. Thank you!
