### ISSUE TITLE
Exception __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by Feverqwe** [ashtuchkin/iconv-lite#205] opened 2018-10-16 05:44 UTC
Hello. After this fix
https://github.com/ashtuchkin/iconv-lite/commit/b8faf3656c65a5d42ab6c7e1cc88a9bd9a80c227
require function return undefined, when use webpack with target electron-renderer

https://github.com/ashtuchkin/iconv-lite/blob/efbbb0937ca8dda1c14e0b69958b9d6f20771f7a/lib/index.js#L144
https://github.com/ashtuchkin/iconv-lite/blob/8faf11c470794be4ecd2cb81bcd6792f85426cb9/lib/index.js#L148

I add rule and fix this bug
```javscript
{
  test: /node_modules[\/\\](iconv-lite)[\/\\].+/,
  resolve: {
    aliasFields: ['main']
  }
}
```

**Comment by ashtuchkin** [comment] 2018-10-16 07:01
Is this the same issue as #204? I have no context about how webpack/electron works out, but looks similar.

**Comment by Feverqwe** [comment] 2018-10-16 07:02
yes, it same problem..

**Comment by joaodforce** [comment] 2020-02-17 14:32
I'm facing the same issue with my Angular app on Electron, However I cannot figure out how to set the webpack rules on the angular compiler.

So as a workaround I'm just reversing the `browser` params back to before the PR.

**Comment by ashtuchkin** [comment] 2020-05-18 04:41
Closing as a duplicate of #204.

**Closed by ashtuchkin** 2020-05-18 04:41 UTC
