### ISSUE TITLE
Uncaught Error: process.binding is not supported

### ISSUE THREAD

**Issue by wenshiqi0** [ashtuchkin/iconv-lite#180] opened 2018-04-08 06:59 UTC
While I update iconv-lite to 0.4.21, I have got an error from iconv-lite.

```
Uncaught Error: process.binding is not supported
    at Object.process.binding (welcome.js:15754)
    at Object.<anonymous> (welcome.js:20672)
    at Object.<anonymous> (welcome.js:20684)
    at __webpack_require__ (welcome.js:679)
    at fn (welcome.js:89)
    at Object.<anonymous> (welcome.js:169979)
    at Object.exports.byteLength (welcome.js:170129)
    at __webpack_require__ (welcome.js:679)
    at fn (welcome.js:89)
    at Object.module.exports (welcome.js:33177)
```

I use iconv-lite in Electron renderer process to decode node Buffer.

**Comment by iygnay** [comment] 2018-04-08 07:10
same problem,  v0.4.19 works fine.

**Comment by ashtuchkin** [comment] 2018-04-08 07:11
Hmm.. all I see in this stack trace is reference to welcome.js, which is not very useful.
Can you check 0.4.20?

**Comment by wenshiqi0** [comment] 2018-04-08 07:14
Same problem on v0.4.20.

```
if (!safer.kStringMaxLength) {
  safer.kStringMaxLength = process.binding('buffer').kStringMaxLength
}
```

**Comment by ChALkeR** [comment] 2018-04-08 09:00
@ashtuchkin Thanks. Will fix shortly.

**Comment by ChALkeR** [comment] 2018-04-08 09:29
@wenshiqi0 I don't think this is caused by Electron. That code works in Electron.
It looks like that error was emitted from webpack/browserify side.

Could you confirm that everything works correctly now?

**Comment by ChALkeR** [comment] 2018-04-08 10:04
I verified that `safer-buffer@2.1.0` failed with browserify with the exact same error and that `safer-buffer@2.1.1` is fine there. I also added browserify tests to the Travis test matrix so this shouldn't happen again ;-).

**Comment by wenshiqi0** [comment] 2018-04-09 02:07
@ChALkeR I'll have a try.

**Comment by ashtuchkin** [comment] 2018-04-17 04:46
@wenshiqi0 did it work?

**Comment by wenshiqi0** [comment] 2018-05-03 10:47
@ashtuchkin It works fine, so I close this issue. Thanks.

**Comment by ashtuchkin** [comment] 2018-05-07 22:11
Ok, closing, thank you!

**Closed by ashtuchkin** 2018-05-07 22:11 UTC
